FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps apps
COPY packages packages
RUN npm install

WORKDIR /app/apps/admin
RUN npm run build

EXPOSE 4173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]

